---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitcoind
  namespace: ln-testnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard
